### ISSUE TITLE
Undoing tab indentation

### ISSUE THREAD

**Issue by jeffalo** [WebReflection/highlighted-code#1]
First off, this is an awesomely simple extension!! Thank you!!!

I noticed that after pressing tab (On Chrome 99.0.4844.82), I can't undo with ctrl+z on my clipboard anymore.

Would it be possible to make it add the indentation without clearing the browser's native undo stack? From a quick Google search, it looks like it might get complicated when supporting multiple browsers.. 

I've previously used https://www.npmjs.com/package/text-field-edit, perhaps using something similar to their implementation would work.

**Comment by WebReflection** [comment]
TBH I've noticed the same, not because I pressed a single char tab and needed to ctrl+z, simply because I've selected multiple rows and then pressed tab and lost all rows without ctrl+z ability ... yes, this is something absolutely needed to make this component usable in the real world, and it's already in my radar ... I'm [just a bit slow these days](https://twitter.com/WebReflection/status/1490618596271267840) and really spending minutes, not even hours, on this ... but I'll get shit done at some point, please bear with me!

**Comment by WebReflection** [comment]
too bad it took forever in Firefox to fix that ... but modern browsers will all work now as expected
